"use client"

import { format } from "date-fns"
import { Printer } from "lucide-react"
import { Button } from "@/components/ui/button"

interface LabExamPrintViewProps {
  exams: any
  patientName: string
  doctorName: string
  doctorSpec?: string
  doctorPhone?: string
  doctorAddress?: string
  date: number
}

export function LabExamPrintView({
  exams,
  patientName,
  doctorName,
  doctorSpec,
  doctorPhone,
  doctorAddress,
  date,
}: LabExamPrintViewProps) {
  if (!exams) return null

  const handlePrint = () => {
    window.print()
  }

  // Parse exams (could be string or array of objects)
  const examList = typeof exams === "string"
    ? [{ name: exams }]
    : Array.isArray(exams)
      ? exams
      : [exams]

  return (
    <div>
      <div className="flex items-center justify-between mb-4 print:hidden">
        <h3 className="font-semibold">Lab Exams</h3>
        <Button variant="outline" size="sm" onClick={handlePrint} className="gap-2">
          <Printer className="h-4 w-4" />
          Print
        </Button>
      </div>

      <div className="rounded-xl border border-border p-6 space-y-6 print:border-0 print:p-0 print:rounded-none">
        {/* Header */}
        <div className="flex justify-between items-start border-b pb-4">
          <div>
            <h2 className="text-lg font-bold">{doctorName}</h2>
            {doctorSpec && <p className="text-sm text-muted-foreground">{doctorSpec}</p>}
            {doctorPhone && <p className="text-sm text-muted-foreground">{doctorPhone}</p>}
            {doctorAddress && <p className="text-sm text-muted-foreground">{doctorAddress}</p>}
          </div>
          <div className="text-right">
            <p className="text-sm text-muted-foreground">Date</p>
            <p className="font-medium">{format(new Date(date), "MMMM d, yyyy")}</p>
          </div>
        </div>

        {/* Patient */}
        <div>
          <p className="text-sm text-muted-foreground">Patient</p>
          <p className="font-medium text-lg">{patientName}</p>
        </div>

        {/* Exams */}
        <div className="space-y-3">
          <h4 className="font-semibold text-primary">Requested Lab Exams</h4>
          <div className="space-y-2">
            {examList.map((exam: any, index: number) => (
              <div key={index} className="flex items-start gap-3 pl-4 border-l-2 border-primary/30">
                <span className="text-sm font-medium text-primary">{index + 1}.</span>
                <div className="space-y-0.5">
                  <p className="font-medium">{exam.name || exam.exam || String(exam)}</p>
                  {exam.notes && <p className="text-sm text-muted-foreground">{exam.notes}</p>}
                  {exam.urgency && <p className="text-sm text-muted-foreground">Urgency: {exam.urgency}</p>}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="border-t pt-4 mt-6">
          <p className="text-sm text-muted-foreground text-center">
            This lab exam request was generated by Pediascrybe
          </p>
        </div>
      </div>
    </div>
  )
}
