"use client"

import { format } from "date-fns"
import { Printer } from "lucide-react"
import { Button } from "@/components/ui/button"

interface PrescriptionPrintViewProps {
  prescriptions: Array<{
    drug: string
    count?: number
    unit?: string
    posology?: string
    dose?: string
    route?: string
  }>
  patientName: string
  doctorName: string
  doctorSpec?: string
  doctorPhone?: string
  doctorAddress?: string
  date: number
}

export function PrescriptionPrintView({
  prescriptions,
  patientName,
  doctorName,
  doctorSpec,
  doctorPhone,
  doctorAddress,
  date,
}: PrescriptionPrintViewProps) {
  if (!prescriptions || prescriptions.length === 0) return null

  const handlePrint = () => {
    window.print()
  }

  const medications = prescriptions

  return (
    <div>
      <div className="flex items-center justify-between mb-4 print:hidden">
        <h3 className="font-semibold">Prescription</h3>
        <Button variant="outline" size="sm" onClick={handlePrint} className="gap-2">
          <Printer className="h-4 w-4" />
          Print
        </Button>
      </div>

      <div className="rounded-xl border border-border p-6 space-y-6 print:border-0 print:p-0 print:rounded-none">
        {/* Header */}
        <div className="flex justify-between items-start border-b pb-4">
          <div>
            <h2 className="text-lg font-bold">{doctorName}</h2>
            {doctorSpec && <p className="text-sm text-muted-foreground">{doctorSpec}</p>}
            {doctorPhone && <p className="text-sm text-muted-foreground">{doctorPhone}</p>}
            {doctorAddress && <p className="text-sm text-muted-foreground">{doctorAddress}</p>}
          </div>
          <div className="text-right">
            <p className="text-sm text-muted-foreground">Date</p>
            <p className="font-medium">{format(new Date(date), "MMMM d, yyyy")}</p>
          </div>
        </div>

        {/* Patient */}
        <div>
          <p className="text-sm text-muted-foreground">Patient</p>
          <p className="font-medium text-lg">{patientName}</p>
        </div>

        {/* Medications */}
        <div className="space-y-3">
          <h4 className="font-semibold text-primary">Rx</h4>
          <div className="space-y-3">
            {medications.map((med, index) => (
              <div key={index} className="pl-4 border-l-2 border-primary/30 space-y-0.5">
                <p className="font-medium">
                  {med.drug}
                  {med.count ? `, ${med.count} ${med.unit ?? "flacon"}` : ""}
                </p>
                {med.dose && <p className="text-sm text-muted-foreground">Dose: {med.dose}</p>}
                {med.route && <p className="text-sm text-muted-foreground">Route: {med.route}</p>}
                {med.posology && <p className="text-sm text-muted-foreground">{med.posology}</p>}
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="border-t pt-4 mt-6">
          <p className="text-sm text-muted-foreground text-center">
            This prescription was generated by Pediascrybe
          </p>
        </div>
      </div>
    </div>
  )
}
