"use client"

import { format } from "date-fns"
import { Printer } from "lucide-react"
import { Button } from "@/components/ui/button"

interface PrescriptionPrintViewProps {
  medication: any
  patientName: string
  doctorName: string
  doctorSpec?: string
  doctorPhone?: string
  doctorAddress?: string
  date: number
}

export function PrescriptionPrintView({
  medication,
  patientName,
  doctorName,
  doctorSpec,
  doctorPhone,
  doctorAddress,
  date,
}: PrescriptionPrintViewProps) {
  if (!medication) return null

  const handlePrint = () => {
    window.print()
  }

  // Parse medication (could be string or array of objects)
  const medications = typeof medication === "string"
    ? [{ name: medication }]
    : Array.isArray(medication)
      ? medication
      : [medication]

  return (
    <div>
      <div className="flex items-center justify-between mb-4 print:hidden">
        <h3 className="font-semibold">Prescription</h3>
        <Button variant="outline" size="sm" onClick={handlePrint} className="gap-2">
          <Printer className="h-4 w-4" />
          Print
        </Button>
      </div>

      <div className="rounded-xl border border-border p-6 space-y-6 print:border-0 print:p-0 print:rounded-none">
        {/* Header */}
        <div className="flex justify-between items-start border-b pb-4">
          <div>
            <h2 className="text-lg font-bold">{doctorName}</h2>
            {doctorSpec && <p className="text-sm text-muted-foreground">{doctorSpec}</p>}
            {doctorPhone && <p className="text-sm text-muted-foreground">{doctorPhone}</p>}
            {doctorAddress && <p className="text-sm text-muted-foreground">{doctorAddress}</p>}
          </div>
          <div className="text-right">
            <p className="text-sm text-muted-foreground">Date</p>
            <p className="font-medium">{format(new Date(date), "MMMM d, yyyy")}</p>
          </div>
        </div>

        {/* Patient */}
        <div>
          <p className="text-sm text-muted-foreground">Patient</p>
          <p className="font-medium text-lg">{patientName}</p>
        </div>

        {/* Medications */}
        <div className="space-y-3">
          <h4 className="font-semibold text-primary">Rx</h4>
          <div className="space-y-3">
            {medications.map((med: any, index: number) => (
              <div key={index} className="pl-4 border-l-2 border-primary/30 space-y-0.5">
                <p className="font-medium">{med.name || med.medication || String(med)}</p>
                {med.dosage && <p className="text-sm text-muted-foreground">Dosage: {med.dosage}</p>}
                {med.frequency && <p className="text-sm text-muted-foreground">Frequency: {med.frequency}</p>}
                {med.duration && <p className="text-sm text-muted-foreground">Duration: {med.duration}</p>}
                {med.instructions && <p className="text-sm text-muted-foreground">Instructions: {med.instructions}</p>}
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="border-t pt-4 mt-6">
          <p className="text-sm text-muted-foreground text-center">
            This prescription was generated by Pediascrybe
          </p>
        </div>
      </div>
    </div>
  )
}
